#!/bin/bash
#
# zt
# ze Tinygrab Clone
# zt takes no arguments (whole screen), -s (selection), and -u (current window)
# released under GPL, whichever version means people have to give attribution
# by hlmtre/Matt Weller
# contributions by Lucifer7 (libnotify and hotkey binding bugfix)
#
# depends:
# xclip
# maim
# notify-send, if you turn it on
#

if [[ -n $1 && "$1" == "-a" ]]; then
	arg="-a"
else
	arg="-s"
fi


CONF="$HOME/.ztrc"
USERNAME=
PORT=
HOSTNAME=
DIR=
URL=

gen_filename() {
	FILENAME=`< /dev/urandom tr -dc A-Za-z0-9_ | head -c8`
	FILENAME="$FILENAME.png"
	meat
}


read_config() {
	PORT=`sed -n '1,1p' $CONF`
	USERNAME=`sed -n '2,2p' $CONF`
	HOSTNAME=`sed -n '3,3p' $CONF`
	DIR=`sed -n '4,4p' $CONF`
	URL=`sed -n '5,5p' $CONF`
}

prompt() {
	echo "Conf not found;"
	read -p "Enter the hostname to upload to: " HOSTNAME
	read -p "Enter the remote sshd port: " PORT
	read -p "Enter the directory to upload to: " DIR
	read -p "Enter remote account username: " USERNAME
	read -p "Enter URL under which images will be available (include trailing slashes): " URL

	touch $CONF
	echo $PORT > $CONF
	echo $USERNAME >> $CONF
	echo $HOSTNAME >> $CONF
	echo $DIR >> $CONF
	echo $URL >> $CONF
}

meat() {
	if [[ "$arg" == "-s" ]]; then
		#notify-send -t 2000 "zt" "Select area to screenshot"
		sleep 0.2
		maim $arg $HOME/Pictures/ss/$FILENAME
		if [[ ! $? -eq 0 ]]; then
			echo "Whoops."
			exit 1
		fi
	else
		sleep 0.2
		maim $HOME/Pictures/ss/$FILENAME
		if [[ ! $? -eq 0 ]]; then
			echo "Whoops."
			exit 1
		fi
	fi
	#notify-send -t 2000 "zt" "Uploading $FILENAME..."
	scp -oPort=$PORT $HOME/Pictures/ss/$FILENAME $USERNAME@$HOSTNAME:$DIR
	return_code=$?
# spit the filename into tr to strip newline, put it into the clipboard with xclip
	echo $URL$FILENAME | tr -d '\n' | xclip -sel clip
	#if [[ $return_code -eq 0 ]]; then
	#	notify-send -t 2000 "zt" "$FILENAME uploaded."
	#else 
	#	notify-send -t 2000 "zt" "$FILENAME upload failed. Return code from scp: $return_code"
	#fi
}

logic() {
	if [[ ! -e $HOME/Pictures/ss/$FILENAME ]]; then 
		meat
	else
		gen_filename
	fi
}


if [[ -s $CONF ]]; then
	read_config
	logic
else
	prompt
	logic
fi
